### PR TITLE
Update of the german translation.

### PR DESCRIPTION
**Pull request by KaiKiehl**
Just some random guy from the internet trying to improve this tool´s german translation. 
Being german myself i went through pretty much all german translations in this file, and tried to improve everything i could, like changing 
"es" to "sie" -> Grammar, 
"Thermalresistent" to "Hitzeresistent" -> better sounding, or 
"Verzeichnisscanner" to "Ladungsscanner" -> different meaning. 
I hope i did everything correctly as i never really worked with GitHub before.
If you have any questions/complaints about any of the changes made, feel free to write me an email at "kai.kiehl@gmx.de".

Kind Regards
Kai Kiehl/CMDR Kiak1

Fly Safe! o7

### CODE REVIEW

**Comment by msarilar** [comment]
Hey,

Thanks a lot! 
This looks good, however be aware that game related stuff needs to map correctly to the name of the item in the game.

When you say:

> "Thermalresistent" to "Hitzeresistent" -> better sounding

Does the game show `Hitzeresistent` or `Thermalresistent` for the blueprint?

I mean that if the name is `Thermalresistent`, then it should be like that in EDEngineer too even if it sounds worse. If it's the other one, then obviously it needed fixing and I'll merge all this.

Could you confirm?

**Comment by KaiKiehl** [comment]
Yeah that´s one of the points i wasn´t really shure about, because i´m playing on the english ED version myself^^ 
But right now i´m booting up the german version, will check all names possible checking

**Comment by msarilar** [comment]
All right ; I believe the contributors who provided localization for German made sure that the name matched to the ones in the game so I'm unfortunately not sure I will merge the PR.

The text translated at the end of the file (which used to be `null`) is however very welcome, feel free to open a new PR with only these changes :)

**Comment by KaiKiehl** [comment]
Ok, did a new PR, that one should be much better/ less problematic.

**Pull request closed without merging**
