### PR TITLE
Desired quantity prototype

### PR DESCRIPTION
**Pull request by jnnnnn**
This is a way to see how many of each material you should keep, and what you need to stock up on.

Problems:

1. It makes the interface more confusing.
2. There's no way to modify the recommended quantity.

image

### CODE REVIEW

**Comment by msarilar** [comment]
Interesting! That's a good idea.

I too, think that it makes the UI quite confusing but I like the idea. Moreover, people are more focus on what ingredient they have too much of and that's why I implemented the thresholds in the latest update.

I think your idea can work really well working alongside the thresholds. You'll find the related property in the `Entry` class ; if it's non-null, it means the user configured it. If the current stock is equal or above that threshold, coloring the ingredient in red would be real nice!

Currently, the thresholds are not available for users with Windows version older than Win8 (because they don't have toast notifications). With that coloring it would allow them to use the feature as well (so you can remove the check here : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Utils/UI/TrayIconManager.cs#L82 otherwise the command will remain disabled for them).

What do you think?

**Comment by jnnnnn** [comment]
Yeah I just realised that the thresholds thing already allows user-set quantities. Your recommendations are good.

**Comment by jnnnnn** [comment]
Here's how it looks now:
image

**Comment by msarilar** [comment]
that's nice

the colored numbers are the difference between the current amount and the threshold, right? I don't think that information is needed though - just knowing if the threshold is reached is enough (with a property like `public bool AboveThreshold => Count >= Threshold;`)

the information about the threshold amount could be displayed in different ways:
* in the tooltip when hovering an ingredient? not sure
* if the threshold is set, you could display it with a slash
    * `CARBON           10` -> threshold not set
    * `CARBON           10 / 30` -> threshold set to 30

the information about whether the threshold is reached could be:
* in the background color of the entry (black with light red tint for instance)
* could be an icon as well, which would be near the existing source icon (to import an icon from an svg or png, open it in inkscape and save it as a .xaml file)

**Comment by jnnnnn** [comment]
Highlighting the background:
image

**Comment by jnnnnn** [comment]
I initially implemented it as showing the total but I prefer the delta because it is easier to see how many extra I have or how many I still need to find, and I can decide that it's not worth finding the last few or throwing away just a couple. Also this way it is easier to see what I have way too much of (for making inventory space) and desperately need (probably the thing I should go find next).

**Comment by jnnnnn** [comment]
I won't be offended if you pass on this change or reimplement it yourself; I'm gonna keep using this branch because I like it this way.

**Comment by msarilar** [comment]
Fair enough :)

I'll do what I have in mind on top of what you did already (in a personal branch) such that if one day you want to fast forward you'll have no conflict.

cheers!

**Comment by msarilar** [comment]
I've updated the app by the way, check it out when you'll have time :)

**Pull request closed without merging**
